### ISSUE TITLE
Consider adding `.text-center` class

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#100]
I would like to suggest a `.text-center` class to align text in the center.

This class is simple, but may be useful for headings, short descriptions, or profile names.  
It may improve layout readability without writing inline styles.

### Why

Right now, if I want to center text, I must write this:

```html
<h1 style="text-align: center;">Hello</h1>
```

But if we add a small utility class like `.text-center`, it would be easier to reuse:

```html
<h1 class="text-center">Hello</h1>
```

It is not required for most layouts, so I understand if we want to keep the CSS file smaller.  
I am opening this issue just to discuss whether this class is needed.

### Optional CSS (if added)

```css
/* 
  Centers text horizontally.
  Useful for headings, intro sections, or simple centered text layouts.
  This is optional because it can also be done with inline styles.
*/
.text-center {
  text-align: center;
}
```

Let me know what you think. I am happy to update or close this if it is not needed.

**Comment by sanemat** [comment]
### Why we prefer utility classes over inline styles

We want to keep HTML clean and easy to read, so it's tempting to use inline styles like this:

```html
<header style="text-align: center;">
```

But inline styles have some problems:

- Hard to override later with normal CSS
- Media queries (like screen size changes) don't work
- Theme changes (like dark mode) also don't work

Using a utility class like `.text-center` solves these problems:

```html
<header class="text-center">
```

Then we can control styles in CSS:

```css
.text-center {
  text-align: center;
}

@media (min-width: 768px) {
  .text-center {
    text-align: left;
  }
}

@media (prefers-color-scheme: dark) {
  .text-center {
    text-align: left;
  }
}
```

This way, we can update or change the design without touching the HTML again.

**Conclusion:**  
Using small utility classes (like `.text-center`) makes the code easier to maintain and more flexible than using inline styles.

**Comment by sanemat** [comment]
### Why we don’t include `.text-center`

We don’t add a `.text-center` class in browser-nano-css.  
Here is why:

#### 1. Text alignment is not about meaning
Centering text is a visual choice.  
It does not change the meaning of your HTML.

We want to focus on clean, semantic HTML.  
Adding a class just for design is not needed.

#### 2. Classes should not grow too much
If we add `.text-center`, people may start asking for:
- `.text-right`
- `.text-justify`
- `.mt-1`, `.px-3`, and many more…

This goes against our goal of keeping things minimal.

#### 3. You can still center text if you want
You have full control.  
Just write your own style if you need it:

```css
.my-centered-block {
  text-align: center;
}
```

Or use inline style:

```html
<header style="text-align: center;">
```

This way, the framework stays clean, and you only add what you really need.

**Conclusion:**  
We don't include `.text-center` because it's about design, not meaning.  
If you want it, you can add it yourself.

**Comment by sanemat** [comment]
### Why we include `.container` and `.flex`, but not `.text-center`

#### `.container` and `.flex` help with structure

These classes help build the layout of the page:

- `.container` gives a max width and spacing
- `.flex` helps align items in a row or column

They are not just about design.  
They help define how the page is built.

#### `.text-center` is only about style

Centering text does not change structure.  
It is just a visual choice.

You can add it yourself if needed.  
But we do not include it by default.

**Goal:**  
Keep only the classes that help with layout and structure.  
Avoid classes that are only for appearance.

**Comment by sanemat** [comment]
### Why we encourage writing your own CSS

Instead of adding many utility classes,  
we think it's better to write your own CSS when needed.

This gives you more control and keeps your HTML clean.

You don’t need to learn a long list of class names.  
You can just write simple, clear styles for your project.

For example:

```css
.my-custom-header {
  text-align: center;
  font-weight: bold;
}
```

This way, you get exactly what you want — nothing more, nothing less.

**Our goal:**  
Use basic CSS. Keep the framework small. Let you decide what to style.
