### ISSUE TITLE
Add `.list-inline` class for horizontal lists

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#101]
I want to suggest a `.list-inline` utility class.

It helps to display list items in a row, for example in a horizontal navigation menu or icon list.

### Why

Some websites use `<ul>` or `<ol>` for navigation or social icons.  
If we want to show them side by side, we need to use `display: flex` and remove default spacing.

Right now, we must write custom CSS like this:

```css
ul.icons {
  display: flex;
  gap: 0.5rem;
  list-style: none;
  padding-left: 0;
}
```

If we add `.list-inline`, it will be easier to reuse and style lists.

### Suggested CSS

```css
/* 
  Displays list items in a row.
  Useful for horizontal navigation or social icon lists.
*/
.list-inline {
  display: flex;
  flex-wrap: wrap;
  gap: var(--spacing-small);
  justify-content: center;
  list-style: none;
  padding-left: 0;
  margin-bottom: var(--spacing-medium);
}
```

### About class name

I think `.list-inline` is better than `.inline` because it is more clear.  
It tells the user that this class is for lists, not for other inline elements.

Let me know what you think!

**Comment by sanemat** [comment]
Thank you for your proposal.

We agree that showing list items in a row is common. Your idea is helpful and the class name `.list-inline` is clear.

However, we will not include this class in the core CSS.

### Reason

This CSS framework is small by design. We try to avoid adding many utility classes.

We focus on:
- Simple HTML with few classes
- Just enough helpers like `.container` or `.flex`
- Letting users write their own styles

For example, users can add this in their own CSS:

```css
ul.icons {
  display: flex;
  gap: 0.5rem;
  list-style: none;
  padding-left: 0;
}
```

This keeps the core CSS clean and flexible for many use cases.

Thank you again for sharing your idea!
