### ISSUE TITLE
Add `.profile-img` class for circular profile pictures

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#102]
I would like to suggest a `.profile-img` utility class.

This class is helpful for showing round profile photos, which are common in personal websites and portfolios.

### Why

Many people want to show their face or avatar in a round image style.  
Right now, we need to write extra CSS like this:

```css
img {
  border-radius: 50%;
  object-fit: cover;
  aspect-ratio: 1 / 1;
}
```

If we add a simple `.profile-img` class, users can do this easily without custom CSS.

### Suggested CSS

```css
/* 
  Makes an image round (circular).
  Useful for profile photos, avatars, or user icons.
*/
.profile-img {
  border-radius: 50%;
  object-fit: cover;
  aspect-ratio: 1 / 1;
}
```

This class is optional, but it makes the user experience better and fits modern design.

Let me know what you think!

**Comment by sanemat** [comment]
Thank you for your idea.

We understand that many people want to show round profile images. Your suggestion is clear and useful.

However, we will not add a `.profile-img` class at this time.

### Reason

This CSS framework is very small on purpose. It does not include many utility classes. We want users to write their own CSS for special styles.

We only include a few helper classes, like `.container` and `.flex`. This helps keep the file small, simple, and easy to understand.

If you want to use a round profile image, you can add this to your own CSS:

```css
.profile-img {
  border-radius: 50%;
  object-fit: cover;
  aspect-ratio: 1 / 1;
}
```

Thank you again for your suggestion!
