### ISSUE TITLE
Add `.tap-target` class for touch-friendly buttons and links

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#103]
I would like to suggest a `.tap-target` utility class.

This class helps make buttons or icon links easier to tap on mobile devices.  
It ensures that the clickable area is at least 48x48 pixels, which follows common accessibility guidelines.

### Why

On small screens, it is important that users can tap elements easily.  
Even if the icon or text looks big, the actual clickable area might be too small.

This class gives enough space to tap without changing the visual size of the icon or text.

It follows the design goals of browser-nano-css: small, clear, and accessible.

### Suggested CSS

```css
/* 
  Makes a button or link easier to tap on touchscreens.
  Keeps the content centered inside a minimum 48x48 pixel box.
  Useful for icon links, buttons, or menu items.
*/
.tap-target {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 48px;
  min-height: 48px;
}
```

Let me know what you think!

**Comment by sanemat** [comment]
### Why 48x48?

48×48 pixels is the minimum recommended touch target size on mobile devices.

- **Google Material Design**: minimum 48x48dp  
- **Apple Human Interface Guidelines**: minimum 44x44pt  

This size helps users tap buttons or links comfortably without mis-tapping.

**Comment by sanemat** [comment]
Thank you for your idea!

We think `.tap-target` is a useful class.  
It matches our design goals: small, clear, and accessible.

### Why we like it

- It improves tap targets on mobile devices.
- It helps with accessibility.
- It does not change how the content looks.
- It is flexible and works with icons, buttons, or links.

We will consider adding `.tap-target` to the next version.

Thank you again for your helpful suggestion!

**Comment by sanemat** [comment]
Thanks again for the idea!

One question: should `.tap-target` always use `display: inline-flex`?

It helps center the content, but it may not work well in all layouts.  
For example, if someone already uses `.flex` on a parent, or wants `block` style, this could cause problems.

Maybe we can split it:

```css
.tap-target {
  min-width: 48px;
  min-height: 48px;
}

.tap-center {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
```

This way, users can choose what they need: size only or size + centering.

What do you think?
