### ISSUE TITLE
Add `.skip-link` helper class

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#108]
I would like to suggest adding a `.skip-link` class to improve accessibility.

### What is it?

`.skip-link` is a class for a link that lets keyboard users skip to the main content of a page.  
This is useful when pages have many repeated elements like navigation menus.

### Why is it important?

- It helps users who use the keyboard or screen readers.
- It follows common accessibility guidelines (for example, WCAG).
- It is simple and does not affect visual design for most users.

### Suggested usage

HTML:

```html
<a href="#main" class="skip-link">Skip to main content</a>
<main id="main">
  <!-- Main page content -->
</main>
```

CSS:

```css
.skip-link {
  position: absolute;
  top: -40px;
  left: 0;
  background: var(--color-background);
  color: var(--color-text);
  padding: var(--spacing-small);
  z-index: 1000;
}
.skip-link:focus {
  top: 0;
}
```

### Why it fits `browser-nano-css`

This class is not for decoration.  
It improves the user experience and accessibility, especially on keyboard and screen reader navigation.

It matches the goals of `browser-nano-css`:
- small and useful
- clear and easy to understand
- accessible by default

Thank you for considering this!
