### ISSUE TITLE
Improve `.tap-target` for better mobile support

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#112]
I would like to suggest adding `display: inline-block` to the `.tap-target` class.

### Why

Right now, `.tap-target` sets `min-width` and `min-height`, but many elements (like `<a>`) are `display: inline` by default. In this case, the size rules do not work.

This is a problem especially on Firefox and Safari. The tap area looks wrong or feels too small.

Adding `display: inline-block` will fix this and make `.tap-target` work as expected.

### Suggested CSS

```css
/* 
  Makes a button or link easier to tap on touchscreens.
  Adds minimum size and sets inline-block to ensure it works with links.
*/
.tap-target {
  display: inline-block;
  min-width: 48px;
  min-height: 48px;
}
```

### Why this is safe

- Most `.tap-target` use cases are for `<a>` or icon links
- `inline-block` is safe inside `<li>`, `<nav>`, or `flex` layouts
- It avoids confusion and works better on all browsers

Thank you for considering this!

**Comment by sanemat** [comment]
![Screenshot_20250331-203856_Firefox.jpg](https://github.com/user-attachments/assets/4afd7d6f-9286-4c9b-be39-88b168d68213)

android firefox

**Comment by sanemat** [comment]
![Screenshot_20250331-205847_Firefox.jpg](https://github.com/user-attachments/assets/f40bd831-730d-451b-95f1-7ff21e625c15)

**Comment by sanemat** [comment]
`inline-flex` looks very clean and helps center the content inside `.tap-target`.  
But we decided not to include it by default because it can have some side effects.

### Why we didn’t use `inline-flex` in the core

Even though it makes the layout look better, it also changes how the element behaves in some cases:

- It affects vertical alignment. This may cause small shifts when used next to text.
- It can break layouts if the content inside is not well-balanced.
- It adds alignment logic to a class that should only control tap size.

For example, in lists or buttons with icons and text, `inline-flex` may not work as expected.

So we only use `inline-block` in the core.  
It keeps the layout stable and lets users decide if they want to center content.

If needed, users can still add `inline-flex` like this:

```css
.tap-target {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
```

This gives more control without breaking simple layouts.

**Comment by sanemat** [comment]
We decided to include only `display: inline-block` in the core `.tap-target` class.

This makes sure the minimum size works on `<a>` and other inline elements,  
without adding layout or alignment rules.

If users want to center the content, they can use `inline-flex` as an optional addition:

```css
.tap-target {
  display: inline-flex;
  align-items: center;
  justify-content: center;
}
```
