### ISSUE TITLE
Add unified heading styles for h1 to h6

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#43]
## Summary

I would like to add a simple and unified style for all heading tags (`h1` to `h6`) to improve visual consistency and readability across devices and browsers.

## Why

Different browsers and devices apply different default styles to headings. This can cause inconsistent layout, spacing, and font rendering. For example:

- **Chrome (desktop):** `h1` is 2em with balanced margins.
- **Safari (iOS):** `h1` often appears smaller and has more spacing.
- **Android Chrome:** `h1` can look thicker or larger depending on device.
- **Firefox:** Slightly different margins and rendering from Chrome.

These differences affect:

- Font size
- Line height
- Font weight
- Top and bottom margins

Even though they may seem small, they add up and break consistency when designing content that works on all devices.

## Suggested Style

```css
h1,
h2,
h3,
h4,
h5,
h6 {
  font-weight: bold;         /* Make all headings bold for emphasis */
  line-height: 1.25;         /* Tighter line spacing for better structure */
  margin-bottom: 0.5em;      /* Space below for clear content flow */
}
```

This keeps heading styles predictable and easy to read.

## What this style does

- It makes all headings bold.  
  → Most browsers do this by default, but we add it just to be sure.
- It sets `line-height: 1.25` for better readability.  
  → This helps text look clear, not too tight.
- It adds `margin-bottom: 0.5em`.  
  → This gives space below headings to separate them from the next content.

## What this style does *not* do

- It does **not** change the default font sizes.  
  → We keep the browser’s natural size differences between `h1` to `h6`.
- It does **not** remove or change the top margin.  
  → We let the browser decide how much space to put above the heading.
- It does **not** use extra variables or complex settings.  
  → The style is simple and easy to override.

## Benefits

- Consistent look across Chrome, Firefox, Safari, Android, and iOS
- Clean and readable content hierarchy
- Better control over layout and spacing
- Easy to maintain and extend later

Let me know if this makes sense or if you'd like to adjust the values. I'm happy to help refine it!
