### ISSUE TITLE
Reset rule

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#45]
## Summary

I want to add a small CSS reset to make layout more consistent in all browsers.

## Why

Even if we want to keep the browser's default look, this kind of reset is still useful.

Browsers use different default styles for margin, padding, and box sizing. These differences can cause layout problems and strange spacing. This reset keeps the basic browser styles (like font size and tag meaning), but removes spacing issues.

### Examples of differences:

- Safari and Firefox often add more space to elements like `ul`, `p`, or `h1` than Chrome
- Chrome uses `content-box` by default, so padding is not included in the width/height
- Mobile browsers sometimes apply spacing in slightly different ways

If we don’t reset this, we might see small layout bugs or extra space, especially on mobile devices.

## Suggested Rule

```css
*,
*::before,
*::after {
  box-sizing: border-box;   /* Include padding and border in width/height */
  margin: 0;                 /* Remove default outer space */
  padding: 0;                /* Remove default inner space */
}
```

## What this rule does

- Selects all elements and pseudo-elements
- Makes layout easier by using `box-sizing: border-box`
- Removes default margin and padding to start clean

## What this rule does not do

- It does **not** remove all default styles (like font sizes)
- It does **not** change how elements look by default
- It does **not** go against the idea of respecting browser styles

## Benefits

- More consistent layout across browsers
- No unexpected spacing
- Easier to calculate box sizes
- Still looks close to the browser's default style

Let me know if this makes sense or if you’d like a smaller reset.
