### ISSUE TITLE
Improve base `body` styles for readability and consistency

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#47]
## Summary

Right now, the `body` only has basic font and color settings.  
I think this is a good start, but we should check if we want to include more base styles.

## Current `body` styles:

```css
body {
  font-family: var(--font-family-base);
  font-size: var(--font-size-base);
  line-height: var(--line-height-base);
  color: var(--color-text);
  background-color: var(--color-background);
}
```

## Why this is helpful

These styles give us:

- A clean and readable font
- Good line spacing for long text
- Safe colors for text and background

They respect browser defaults while improving readability and layout.

## Question

Should we add more base styles to `body`?  
Or is this already enough based on our goals (lightweight, mobile-first, simple, customizable)?

Let’s discuss what we might include or leave out.

**Comment by sanemat** [comment]
Discussions about the purpose and scope of `browser-nano-css`, we propose improving the `body` element with some small but meaningful base styles.

We discuss:
- Keeping the CSS small and minimal
- Improving readability and mobile layout
- Respecting browser defaults as much as possible
- Avoiding styles that add interactivity or visual effects

These changes aim to improve layout consistency and accessibility without going against our core values.

---

### ✅ Goals this supports

- **Mobile-first**: Makes content behave well on small screens.
- **Lightweight**: All styles are very small and compress well.
- **Readability & Accessibility**: Better font control and layout safety.
- **Simplicity**: No visual gimmicks or advanced layout tricks.
- **Customizable**: Still easy to override using CSS variables.

---

### 💡 Final `body` styles

```css
body {
  font-family: var(--font-family-base);
  font-size: var(--font-size-base);
  line-height: var(--line-height-base);
  color: var(--color-text);
  background-color: var(--color-background);

  min-height: 100vh;         /* Makes background color fill the screen */
  word-break: break-word;    /* Avoids layout issues with long words */
  text-size-adjust: 100%;    /* Stops mobile Safari from shrinking text */
  margin: 0;                 /* Clear top-level reset, matches global reset */
}
```

---

### 🔍 Why these additions?

| Style                     | Why it was added |
|---------------------------|------------------|
| `min-height: 100vh`       | Prevents background from cutting off on short pages, especially on mobile |
| `word-break: break-word`  | Prevents layout overflow from long words or URLs |
| `text-size-adjust: 100%`  | Stops automatic text shrinking on iOS Safari |
| `margin: 0`               | Matches global reset and avoids surprises in layout spacing |

---

### 🛑 What we decided NOT to include

We also discussed these styles but decided not to include them, to stay minimal and avoid visual or interactive changes.

| Style                          | Why it was excluded |
|--------------------------------|---------------------|
| `scroll-behavior: smooth`      | It adds interaction behavior. Our goal is layout-only. |
| `-webkit-tap-highlight-color`  | Removes visual feedback some users rely on. Optional per project. |
| `text-rendering: optimizeLegibility` | Might impact performance on some devices. Out of scope. |
| `letter-spacing`               | Font-specific and subjective. Best left to user choice. |
| `cursor: default`              | Already default in browsers. No need to declare. |

---

These base styles improve layout without changing browser behavior.  
They give a clean, usable starting point while respecting the project's core values.

Let us know if you agree or want to adjust anything!
