### ISSUE TITLE
Thinking about basic `<a>` (link) styles for accessibility and readability

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#60]
## Summary

We want to add simple and clear styles for links (`<a>` tags) in `browser-nano-css`.  
This issue is not a final decision. It shows ideas and thoughts from a discussion.

We care about:

- **Accessibility** – all users, including keyboard and color-blind users
- **Readability** – links should not disturb the text
- **Clarity** – users should know something is a link
- **Consistency** – links should look and behave the same in all modern browsers
- **Customization** – easy to change color or style using variables
- **Simplicity** – keep the code small and easy to understand

---

## What we discussed

We talked about different ideas for how links should look and behave:

- Should links always be underlined? Or only when hovered or focused?
- What color should we use? Something readable and high contrast?
- Should we support keyboard focus with `:focus`?
- Should we always use underlines so color-blind users can see the link?
- Should we add a `--color-link` variable for easy theming?
- Should visited links have a different color?
- Should we use `text-decoration-skip-ink` to make underlines cleaner?
- Should we increase underline thickness on hover/focus?
- Should links be slightly bold for balance?
- How much styling is too much for a minimalist CSS?

These are open questions, not final answers.

---

## Example style (for discussion only)

```css
:root {
  --color-link: #0066ff;
}

a {
  color: var(--color-link);
  text-decoration: underline;
  text-decoration-skip-ink: auto;
}

a:hover,
a:focus {
  text-decoration-thickness: 2px;
}
```

This idea keeps links clear and readable.  
It supports keyboard users and can be changed using a CSS variable.

---

## Questions

- Should the underline always be shown, or only on hover/focus?
- Should visited links have their own style?
- Is this simple enough for the default template?
- Should this be part of the core or an optional extension?

Let’s share ideas and see what fits the project best.

**Comment by sanemat** [comment]
### Mobile-first note on link visibility

We also considered how link styles behave differently on desktop and mobile devices:

- On desktop, many websites hide underlines by default and show them on hover
- But mobile devices do not support `:hover` well
- If we hide underlines, mobile users might not notice the link
- A mobile-first CSS should always show underlines to make links clear and easy to tap

**Comment by sanemat** [comment]
## ✅ Link Style — Summary and Recommendation

We discussed how to style `<a>` elements in a way that balances:

- **Accessibility**
- **Readability**
- **Clarity**
- **Minimalism**
- **Customizability**

---

### 🔒 Must (Required for minimum accessibility and usability)

| Rule                        | Why |
|-----------------------------|-----|
| `color` with high contrast | Makes the link readable and visible |
| `:hover` OR `:focus` style | Adds interaction feedback |
| `:focus` state              | Required for keyboard accessibility |
| Consistent underline or other signal | Ensures color-blind users can identify links |

---

### 👍 Better (Improves experience without breaking minimalism)

| Rule                              | Why |
|-----------------------------------|-----|
| Always underline (`text-decoration: underline`) | Makes links identifiable without relying on color |
| `text-decoration-skip-ink: auto`  | Improves visual appearance of underlines |
| `text-decoration-thickness` on hover/focus | Adds subtle feedback |
| `--color-link` variable           | Allows easy theme customization |
| `a:visited` style                 | Optional — helps in document-style pages |
| `font-weight: 500` (optional)     | Slight visual emphasis without adding color |

---

### 🧩 Final Recommendation

```css
:root {
  --color-link: #0066ff;
}

a {
  color: var(--color-link);
  text-decoration: underline;
  text-decoration-skip-ink: auto;
}

a:hover,
a:focus {
  text-decoration-thickness: 2px;
}
```

---

### 📌 Notes

- You can override `--color-link` to match your theme.
- This style supports keyboard navigation and color-blind accessibility.
- Still small and lightweight, respecting our design goals.
- You may add `a:visited { color: ...; }` in a separate layer if needed.

Let us know if this should go into the core or be an optional extension!

**Comment by sanemat** [comment]
```css
:root {
  --color-link: #0066ff; /* Bright and readable blue for links */
}

a {
  color: var(--color-link);                 /* Use custom link color */
  text-decoration: underline;              /* Always show underline for clarity (especially on mobile) */
  text-decoration-skip-ink: auto;          /* Make underlines skip descenders (like "g", "j") for better readability */
}

a:hover,
a:focus {
  text-decoration-thickness: 2px;          /* Make underline thicker on hover or focus for better feedback */
}
```
