### ISSUE TITLE
Add spacing rules for `p`, `ul`, and `ol`

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#68]
## Summary

I want to add a small spacing rule for text blocks like `<p>`, `<ul>`, and `<ol>`.  
This will help keep layout and text easier to read.

---

## Why

Different browsers use different default margins for paragraphs and lists.  
Sometimes they are too big or too small, and it causes uneven layout.  
This rule replaces the default spacing with a simple, clear, and easy-to-customize value.

We also define spacing variables so people can change spacing if they want.

---

## Proposed CSS

```css
:root {
  --spacing-small: 0.5rem;
  --spacing-medium: 1rem;
  --spacing-large: 2rem;
}

p,
ul,
ol {
  margin-bottom: var(--spacing-medium); /* Clear space between content blocks */
}
```

---

## Benefits

- Better readability and rhythm between text blocks
- Follows our design idea: "Explicit over Implicit"
- Works well for mobile and desktop
- Small size, safe to include in base styles
- Easy to customize with spacing variables

---

## Optional ideas

- Use spacing variables for headings too (maybe later)
- Only apply spacing to elements that are not last-child (if needed)

Let me know if this should be added to the core.
