### ISSUE TITLE
Add Minimal Form Styles

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#72]
### Goal

We want to define minimal CSS styles for form elements. The style should follow the current design philosophy of `browser-nano-css`.

The form should look clean and readable on modern browsers, with good spacing, simple borders, and accessible focus styles.

### Why

- Keep design consistent with the rest of the system
- Improve usability of inputs, buttons, and labels
- Make it easier to use basic forms with no extra classes

### What to Include

- Styles for: `input`, `textarea`, `select`, `label`, `button`, and `fieldset`
- Use existing design tokens (`--spacing-small`, `--color-link`, etc.)
- Inherit font and color from the parent
- Add `outline` for focus to support keyboard users
- Add padding and `border-box` layout

### Optional

- A class or utility for spacing between form elements (like `.form-group`)
- Optional `.error` style for validation messages or error borders

### Reference

Here is a draft of what the styles could look like:

```css
input,
textarea,
select {
  font: inherit; /* Makes form elements visually match the rest of the UI */
  color: inherit; /* Ensures consistent text color across components */
  background-color: var(--color-background); /* Keeps background aligned with site theme */
  border: 1px solid #ccc; /* Adds a clear visual boundary without looking heavy */
  border-radius: 4px; /* Softens edges for a modern, friendly appearance */
  padding: var(--spacing-small); /* Improves tap target size and readability */
  width: 100%; /* Ensures mobile-first full-width inputs for better UX on small screens */
  max-width: 100%; /* Prevents layout-breaking overflow in narrow containers */
  box-sizing: border-box; /* Simplifies layout calculations and prevents unexpected sizing */
}

input:focus,
textarea:focus,
select:focus {
  outline: 2px solid var(--color-link); /* Makes focus visible for keyboard and accessibility users */
  outline-offset: 2px; /* Separates outline from content for better contrast and clarity */
}

label {
  display: block; /* Makes layout predictable when stacking label + input */
  margin-bottom: 0.25rem; /* Creates space between label and input for readability */
  font-weight: bold; /* Helps users quickly scan and understand form structure */
}

fieldset {
  border: none; /* Removes outdated browser styling that may clash with the design */
  margin: 0 0 var(--spacing-medium) 0; /* Adds space between grouped sections */
  padding: 0; /* Removes default spacing that is often inconsistent across browsers */
}

button {
  font: inherit; /* Keeps buttons visually consistent with surrounding text */
  padding: 0.5rem 1rem; /* Makes button easy to tap or click, especially on mobile */
  background-color: var(--color-text); /* Ensures strong contrast for accessibility */
  color: var(--color-background); /* Reuses background color token to keep the design balanced */
  border: none; /* Removes native borders that can look inconsistent */
  border-radius: 4px; /* Matches form inputs and adds visual harmony */
  cursor: pointer; /* Makes it clear that the button is clickable */
}

button:focus {
  outline: 2px solid currentColor; /* Reuses text color to maintain visual connection */
  outline-offset: 2px; /* Improves visibility of the focus ring without overlap */
}
```

**Comment by sanemat** [comment]
## 💡 Discussion: Prioritizing Form Element Styles

This comment evaluates which form styles should be included in `browser-nano-css`, based on its design philosophy:

- Respect browser defaults unless they cause confusion
- Be explicit about layout, readability, and accessibility
- Stay minimal, fast, and consistent across platforms

### ✅ Priority Scale

| Level | Meaning |
|-------|---------|
| 1 – Must | Essential for usability or consistency. Should always be included. |
| 2 – Strongly Recommended | Improves user experience and consistency. Not critical, but valuable. |
| 3 – Recommended | Helpful in many cases. May be left out to keep the CSS smaller. |
| 4 – Optional | Useful depending on the project, but not required for base styling. |
| 5 – Out of Scope | Too complex, too specific, or against the design goals. |

---

### 📋 Evaluation: Form Style Candidates

| Feature | Level | Reason |
|--------|-------|--------|
| Basic styles for `input`, `textarea`, `select` (padding, border, font, box-sizing) | 1 – Must | Normalizes look across browsers and ensures mobile-first usability. |
| `label` with `display: block` and spacing | 2 – Strongly Recommended | Improves form readability and layout flow. |
| Base styles for `button` (padding, background, cursor) | 1 – Must | Prevents inconsistent or unusable default buttons. |
| `:focus` outline styles | 1 – Must | Crucial for accessibility (keyboard navigation). |
| `fieldset` reset | 2 – Strongly Recommended | Avoids outdated browser styles that break layout. |
| `disabled` state styling (e.g. opacity) | 3 – Recommended | Makes form state more visible to the user. |
| Optional spacing utility (e.g. `.form-group`) | 4 – Optional | Helpful for layout but not essential for all use cases. |
| `.error` class for validation feedback (e.g. red border) | 3 – Recommended | Improves form feedback clarity, but implementation varies by app. |
| Dark mode support via variables | 2 – Strongly Recommended | Keeps form fields consistent with base color scheme. |
| `::placeholder` color style | 4 – Optional | Improves subtle clarity, but may be left to app-specific CSS. |
| Custom styling for checkboxes / radios | 5 – Out of Scope | Too complex and browser-specific for a minimal CSS file. |
| Grid layouts (e.g. two-column form) | 5 – Out of Scope | Layout concerns are better handled with utility classes or HTML. |
| `.error-message` helper style | 3 – Recommended | Improves form UX but may introduce component-level complexity. |

---

### 📌 Suggestion for Inclusion

| Level | Include Now |
|-------|-------------|
| 1     | ✅ Basic form controls, `button`, `label`, `:focus` outline |
| 2     | ✅ `fieldset` reset, dark mode support |
| 3     | ➕ Consider `.error` and `disabled` styles in a future update |

This helps keep `browser-nano-css` lightweight and accessible, while improving default form behavior across modern browsers.

**Comment by sanemat** [comment]
```css
:root {
  --border-radius: 4px;
  --color-border: #ccc;
  --color-focus-ring: var(--color-link); /* fallback to link color */
}

input,
textarea,
select {
  font: inherit; /* Makes form elements visually match the rest of the UI */
  color: inherit; /* Ensures consistent text color across components */
  background-color: var(--color-background); /* Keeps background aligned with site theme */
  border: 1px solid var(--color-border); /* Adds a clear visual boundary without looking heavy */
  border-radius: var(--border-radius); /* Softens edges for a modern, friendly appearance */
  padding: var(--spacing-small); /* Improves tap target size and readability */
  width: 100%; /* Ensures mobile-first full-width inputs for better UX on small screens */
  max-width: 100%; /* Prevents layout-breaking overflow in narrow containers */
  box-sizing: border-box; /* Simplifies layout calculations and prevents unexpected sizing */
}

input:focus,
textarea:focus,
select:focus {
  outline: 2px solid var(--color-focus-ring); /* Makes focus visible for keyboard and accessibility users */
  outline-offset: 2px; /* Separates outline from content for better contrast and clarity */
}

label {
  display: block; /* Makes layout predictable when stacking label + input */
  margin-bottom: 0.25rem; /* Creates space between label and input for readability */
  font-weight: bold; /* Helps users quickly scan and understand form structure */
}

fieldset {
  border: none; /* Removes outdated browser styling that may clash with the design */
  margin: 0 0 var(--spacing-medium) 0; /* Adds space between grouped sections */
  padding: 0; /* Removes default spacing that is often inconsistent across browsers */
}

button {
  font: inherit; /* Keeps buttons visually consistent with surrounding text */
  padding: 0.5rem 1rem; /* Makes button easy to tap or click, especially on mobile */
  background-color: var(--color-text); /* Ensures strong contrast for accessibility */
  color: var(--color-background); /* Reuses background color token to keep the design balanced */
  border: none; /* Removes native borders that can look inconsistent */
  border-radius: var(--border-radius); /* Matches form inputs and adds visual harmony */
  cursor: pointer; /* Makes it clear that the button is clickable */
}

button:focus {
  outline: 2px solid currentColor; /* Reuses text color to maintain visual connection */
  outline-offset: 2px; /* Improves visibility of the focus ring without overlap */
}
```
