### ISSUE TITLE
Add basic responsive styles

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#78]
### Summary

I want to suggest adding a few simple responsive CSS rules to `browser-nano.css`. These are only the important and useful ones. They help make the layout better on all screen sizes without making the file bigger or harder to use.

---

### Why?

Even though `browser-nano.css` is small and mobile-first, a few styles are still needed:

- **Must-have**: To stop things like images from breaking the layout
- **Strongly recommended**: To make layouts and text easier to read on big screens

We can fix this with just a few lines of CSS.

---

#### ✅ Must-Have

```css
/* Container with max width */
.container {
  max-width: 960px;
  margin: 0 auto;
  padding: var(--spacing-medium);
}

/* Keep media from going outside the screen */
img,
video,
table {
  max-width: 100%;
  height: auto;
}
```

#### 🔶 Strongly Recommended

```css
/* Flex layout for simple layout changes */
.flex {
  display: flex;
  flex-direction: column;
  gap: var(--spacing-medium);
}

@media (min-width: 768px) {
  .flex {
    flex-direction: row;
  }

  :root {
    --font-size-base: 1.125rem;
  }
}
```

#### 📱 Viewport meta tag (for HTML, not CSS)

```html
<!-- Add this to HTML head -->
<meta name="viewport" content="width=device-width, initial-scale=1">
```

---

### Where to Add

You can put these rules at the end of `browser-nano.css`, with this kind of comment:

```css
/* =======================================
   Responsive Core Styles (Minimal Set)
   - Must + Strongly Recommended only
   - Added for better use on all screen sizes
======================================= */
```

---

### Fits the Design Goals

This proposal matches what `browser-nano.css` is all about:

- ✅ No JavaScript
- ✅ Very few class names
- ✅ Optional and easy to read
- ✅ Works well in all browsers
- ✅ Uses simple, supported CSS

---

### Feedback Welcome

Please let me know if this sounds good. I'm happy to help with a pull request!
