### ISSUE TITLE
Add basic styles for `<figure>` and `<figcaption>`

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#81]
#### Summary

I would like to suggest adding minimal default styles for `<figure>` and `<figcaption>` to improve consistency and readability.

#### Current Behavior

Right now, the `browser-nano.css` file does not include any specific styles for `<figure>` and `<figcaption>`. These elements display with browser defaults only.

#### Suggested Styles

```css
figure {
  margin-bottom: var(--spacing-medium);
}

figcaption {
  text-align: center;
  font-size: 0.875rem;
  color: var(--color-text);
  margin-top: var(--spacing-small);
}
```

#### Why this is useful

- Keeps the layout consistent with other elements (like `p`, `ul`, and `label`)
- Helps users understand that `figcaption` is related to the image
- Makes the caption easier to read, especially on mobile
- These styles are small and follow the design rules (explicit, readable, and mobile-first)

#### Discussion

Should we include these styles by default? Or maybe provide them as a utility class (like `.figure`)?

Also, do we need to support horizontal layout (like `<figure class="flex">`) or just vertical for now?

Let me know what you think!
