### ISSUE TITLE
Add basic styles for `<legend>` in forms

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#85]
Right now, the `<legend>` element inside `<fieldset>` has no custom style.

This can look inconsistent across browsers, and the spacing is too small between the title and form fields.

Since `legend` is used as a title for grouped form fields, it makes sense to give it basic styling for clarity and accessibility.

---

### ✅ Proposal

Add this to the CSS:

```css
legend {
  font-weight: bold; /* Make the group title clear and readable */
  margin-bottom: var(--spacing-small); /* Add space between the title and the form fields */
  display: block; /* Prevent bugs in Safari and improve layout control */
}
```

---

### 💡 Why this helps

- Makes form groups more readable
- Keeps spacing consistent with other elements
- Improves cross-browser layout (especially Safari)
- Still minimal and fits with `browser-nano-css` design

Let me know what you think!
