### ISSUE TITLE
Add a default `resize` rule for `<textarea>`

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#86]
Right now, the `<textarea>` element does not have a `resize` rule.  
Because of this, different browsers show different resize behaviors.

To make the layout more consistent and user-friendly, we can set it to resize only vertically.

---

### ✅ Proposal

Add this to the CSS:

```css
textarea {
  resize: vertical; /* Allow resizing up and down only, to keep layout clean */
}
```

---

### 💡 Why this helps

- Keeps the layout from breaking on small screens
- Prevents horizontal scroll or overflow issues
- Keeps the design consistent across browsers
- Still allows users to resize when they need more space

Let me know if this makes sense for `browser-nano-css`!
