### ISSUE TITLE
Add support for `prefers-reduced-motion` for better accessibility and performance

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#87]
## Add support for `prefers-reduced-motion` for better accessibility and performance

Right now, `browser-nano-css` does not include any animations or transitions by default, which is good for performance.

However, some tools like PageSpeed Insights and Lighthouse check for support of `prefers-reduced-motion` as part of accessibility and performance audits.

Even if we don’t use animations now, adding a small rule to respect the user’s system preference can improve scores and future-proof the CSS.

---

### ✅ Proposal

Add this to the CSS:

```css
/* =======================================
   Accessibility Support
   - Respect user preference for reduced motion
======================================= */
@media (prefers-reduced-motion: reduce) {
  * {
    animation: none !important; /* Turn off animations for users who prefer reduced motion */
    transition: none !important; /* Turn off transitions to avoid motion effects */
  }
}
```

---

### 💡 Why this helps

- Improves accessibility for users with motion sensitivity
- Improves audit results in tools like PageSpeed Insights
- Safe to include, even if we don’t use motion now

Let me know what you think!
