### ISSUE TITLE
Add CLS protection styles for better layout stability

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#90]
Right now, `browser-nano-css` does not include specific rules to reduce **Cumulative Layout Shift (CLS)**, but it already follows good practices like using system fonts and small file size.

To further improve layout stability, especially on forms and images, we can add a few minimal CSS rules that help prevent shifts during page load or input focus.

---

### ✅ Proposal

Add the following to the relevant sections:

#### For images (under "Media and Figures"):

```css
img,
video,
table {
  max-width: 100%;
  height: auto;
  aspect-ratio: auto; /* Reserve space even when width/height is missing */
}
```

#### For form controls (under "Base Styles"):

```css
input,
textarea,
select {
  ...
  min-height: 2.5rem; /* Keep form element height stable to prevent CLS */
}

button {
  ...
  min-height: 2.5rem; /* Prevent layout shifts when buttons change size */
}
```

#### For legend (under "Base Styles" or create new if missing):

```css
legend {
  font-weight: bold;
  margin-bottom: var(--spacing-small);
  display: block; /* Avoid layout bugs in Safari */
  min-height: 1.5rem; /* Prevent layout shifts from inconsistent height */
}
```

---

### 💡 Why this helps

- Prevents unexpected layout jumps on slow connections or during form interaction
- Helps improve CLS score in Core Web Vitals
- Still keeps the CSS minimal and readable

Let me know what you think!
