### ISSUE TITLE
Improve focus visibility for `<button>` when using the keyboard

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#93]
When using the keyboard (Tab key), the focus on `<button>` is hard to see in some cases.  
It uses `outline: 2px solid currentColor`, but the contrast between the button background and the focus ring is sometimes too low.

This can make it hard to tell which button is focused.

---

### ✅ Proposal

Update the `button:focus` rule to use a stronger outline color for better visibility.

```css
button:focus {
  outline: 2px solid var(--color-focus-ring); /* Use strong and consistent color for keyboard focus */
  outline-offset: 2px; /* Create space around the outline for better clarity */
}
```

---

### 💡 Why this helps

- Makes keyboard navigation more clear and accessible
- Keeps focus color consistent with inputs and links
- Uses the existing `--color-focus-ring` token

Let me know what you think!
