### ISSUE TITLE
Use `--color-focus-ring` for `<a>:focus` to improve visibility

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#94]
Right now, the `a:focus` style uses:

```css
a:focus {
  outline: 2px solid currentColor;
  outline-offset: 2px;
}
```

This works in many cases, but when the link color is light or gray, the outline is hard to see.  
It can be confusing for keyboard users who use the Tab key to navigate.

---

### ✅ Proposal

Use the `--color-focus-ring` variable for consistent focus outline color, like other elements (inputs, buttons):

```css
a:focus {
  outline: 2px solid var(--color-focus-ring); /* Use strong and consistent color for keyboard focus */
  outline-offset: 2px; /* Prevent overlap with underline */
}
```

---

### 💡 Why this helps

- Makes focus easier to see on all links
- Matches the style of other focused elements
- Works better for accessibility and user experience

Let me know what you think!
