### ISSUE TITLE
Add `.visually-hidden` and `.focusable:focus` classes for accessibility

### ISSUE THREAD

**Issue by sanemat** [sanemat/browser-nano-css#99]
I would like to add two CSS classes: `.visually-hidden` and `.focusable:focus`.

These classes help screen reader users and keyboard users.  
They are useful for a "Skip to content" link at the top of the page.

### Why

Some users do not use a mouse. They use the `Tab` key to move through the page.  
If we add a link like this at the top:

```html
<a href="#main" class="visually-hidden focusable">Skip to content</a>
```

Then the user can press `Tab` and jump to the main content.  
This is helpful on pages with many menu links or headers.

These classes are small but very useful. We should also include them in the README.

### Suggested CSS

```css
/* 
  Hides content visually but keeps it available for screen readers.
  Use this class for accessibility, like skip links or hidden labels.
*/
.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
  white-space: nowrap;
  border: 0;
}

/* 
  When the user focuses the link (for example, by pressing Tab),
  show the link so they can see and use it.
*/
.focusable:focus {
  position: static;
  width: auto;
  height: auto;
  margin: 1rem;
  padding: 0.5rem 1rem;
  background: #000;
  color: #fff;
  z-index: 1000;
  text-decoration: none;
}
```

Let me know if it is okay to add these. Thank you!
